version: '3.7'
services:
  technical-maintenance-schedule:
    container_name: technical-maintenance-schedule
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - JWT_TOKEN_KEY=JG#JGF^Vdf&^6f*%&^2edv237td6
      - PAYWAY_API_KIOSKCASH_KEY=de762450-f0bf-4b74-9801-feaa179c83ad
      - PAYWAY_API_MESSAGES_KEY=xKgai68ZgPI2wtpuT4pItd7uTOUc0Z1s
      - CRON_SCHEDULE=0 0/15 8-17 ? * MON-SAT
      - CRON_TIMEZONE=Africa/Kampala
      - GRASSHOPPER_API_KEY=8098192c-09ae-4bf1-ae54-6c5ada6facd0
      - LAT_HEAD_OFFICE=0.3277179452821463
      - LONG_HEAD_OFFICE=32.605587850546584
    ports:
      - "8080:8080"
    #    restart: always
    depends_on:
      - postgres_db
    networks:
      - technical-maintenance-schedule-network

  postgres_db:
    image: postgres:13.3
    container_name: postgres_technical-maintenance-schedule
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=technical_maintenance_schedule
    ports:
      - "5432:5432"
    #    restart: always
    networks:
      - technical-maintenance-schedule-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  technical-maintenance-schedule-network:

volumes:
  db-data: